### ISSUE TITLE
+/@E.  turns off output from rest of session

### ISSUE THREAD

**Issue by plj541** [jsoftware/j-playground#85] opened 2022-06-03 04:12 UTC
+/'or'E. 'oror'
2
   'Worked'
Worked
     'or'+/@E. 'oror'

   'No output from input, including from this line'

**Comment by joebo** [comment] 2022-06-03 14:28
Thanks for logging. This is likely related to
https://github.com/jsoftware/j-playground/issues/34#issuecomment-1140047578
which is still a puzzle

**Comment by HenryHRich** [comment] 2022-06-03 14:58
Something in the execution of the verb returned a zero value without
signaling an error.  There is a flag in je.h that you can set to segfault
when that happens (I haven't tested it recently)

Henry Rich

**Comment by joebo** [comment] 2022-06-04 13:06
> Something in the execution of the verb returned a zero value without signaling an error. There is a flag in je.h that you can set to segfault when that happens (I haven't tested it recently) Henry Rich


This sounds like the clue we need. Thanks Henry.

**Comment by plj541** [comment] 2022-06-07 01:57
I made a mistake copying the error, the failing line should be:
   'or'+/@E. 'oror'
My mistake was fortuitous, while 
   'or'+/@e. 'oror'
doesn't turn off all output, it doesn't return a result either.
  a=. 'or'+/@e. 'oror'
  a
|value error: a
|[-0]

**Comment by joebo** [comment] 2022-06-15 14:25
> Something in the execution of the verb returned a zero value without signaling an error. There is a flag in je.h that you can set to segfault when that happens (I haven't tested it recently) Henry Rich

This was a great clue. I've narrowed down the problem but not sure yet how to fix. 

With some hacky print debugging, I found that atcomp is calling under2, which it shouldn't be...

j.h
```
#define R0 {printf("R0\n"); emscripten_run_script("console.log(stackTrace())"); R 0;}
```

Outputs
```
R0
VM414:1 Error
    at jsStackTrace (index.js:1744:19)
    at stackTrace (index.js:1789:16)
    at eval (eval at _emscripten_run_script (index.js:4522:7), <anonymous>:1:13)
    at _emscripten_run_script (index.js:4522:7)
    at jtfix (index.wasm:0x214092)
    at jtunder2 (index.wasm:0x116732)
    at byn$fpcast-emu$jtunder2 (index.wasm:0x28e8d6)
    at atcomp (index.wasm:0xb3bcf)
    at byn$fpcast-emu$atcomp (index.wasm:0x28b286)
    at jtparsea (index.wasm:0x198d60)
```

Working up the chain in cu.c

```
static DF2(jtunder2){F2PREFIP;DECLFG;A fullf; 
printf("in jtunder2\n");
printf("sv->localuse.lu1.wvb = %d",sv->localuse.lu1.wvb);
//emscripten_run_script("console.log(stackTrace())");
RZ(fullf=atop(invrecur(fix(sv->localuse.lu1.wvb,sc(FIXASTOPATINV))),sv->fgh[2]));
```

Shows 

```
in jtunder2
(index):1237 sv->localuse.lu1.wvb = 0W is: 0
```

In af.c

```
// On internal calls, self is an integer whose value contains flags.  Otherwise zeroionei is used
DF1(jtfix){PROLOG(0005);A z;
printf("W is: %d\n",w);
 ARGCHK1(w);
 ```

ARCHK1 is returning 0 because w is 0. w is 0 because lu1.wvb isn't sent. lu1.wvb isn't set because jtunder wasn't called,  and jtunder wasn't even supposed to be called for ```'or'+/@e. 'oror'``` or ```{' +./@:e. '\"{['"```... Using makefile.linux, it does not call jtunder2 for that statement (as expected) and it returns correctly.

**So, why is atcomp picking the wrong function to call? Maybe something in here?**

vcompsc.c

```
// Here to choose the function to use, after the arguments are known.
// We require the ranks to be <2 for processing here except for @e., which requires that the result of e. have rank<2
// If the form is [: f/ g  and g is a simple comparison, use f/@g code for higher ranks
// If no routine found, return 0 to failover to normal path
// result bits 0-1 indicate postprocessing needed: 0x=none, 10=+./ (result is binary 0 if search completed), 11=*./ (result is binary 1 if search completed)
AF jtatcompf(J jt,A a,A w,A self){I m;
 ARGCHK2(a,w);
 m=FAV(self)->flag&255;
 if((m&6)!=6){   // normal comparison
  // verify rank is OK, based on operation
  if((AR(a)|AR(w))>1){R (m>=(4<<3))?(AF)jtfslashatg:0;}   // If an operand has rank>1, reject it unless it can be turned to f/@g special. postflags are 0
  ASSERT(AN(a)==AN(w)||((AR(a)&AR(w))==0),EVLENGTH)   // agreement is same length or one an atom - we know ranks<=1
  if(unlikely((-AN(a)&-AN(w)>=0)))R0;  // if either arg empty, skip our loop
  // split m into search and comparison
  I search=m>>3; I comp=m&7;
  // Change +./ to i.&1, *./ to i.&0; save flag bits to include in return address
  I postflags=(0xc0>>search)&3; search=(0x0143210>>(search<<2))&15;  // flags: 00 00 00 00 00 10 11, rev/overlap to 11000000   search: 0 1 2 3 4 1 0
  // Change i.&1@:comp to i.&0@:compx, sim for i:  XOR comp with 000 001 000 110 000 110
  comp^=(0x606010>>(((search&1)+(comp&6))<<2))&7; search>>=1;  // complement comp if search is i&1; then the only search values are 0, 2, 4 so map them to 012.  Could reorder compares to = ~: < >: > <: to save code here
  if(!((AT(a)|AT(w))&((NOUN|SPARSE)&~(B01+INT+FL)))){
   // numeric types that we can handle here, for sure
   R (AF)((I)atcompxy[6*9*search+9*comp+3*(AT(a)>>INTX)+(AT(w)>>INTX)]+postflags);
  }
  // Other types have a chance only if they are equal types; fetch from the appropriate table then
  if(ISDENSETYPE(AT(a)&AT(w)|((AT(a)|AT(w))&SPARSE),LIT+C2T+C4T+SBT)){R (AF)((I)(AT(a)&LIT?atcompC:AT(a)&C2T?atcompUS:AT(a)&C4T?atcompC4:atcompSB)[6*search+comp]+postflags);}
  R 0;
 }else{  // E. (6) or e. (7)
  if(unlikely((AR(a)|AR(w))>1)){if(!(m&1)||AR(a)>(AR(w)?AR(w):1))R0;}  // some rank > 1, fail if E. or (e. returns rank>1)
  if(unlikely(((m&1)|(AN(a)-1))==0))R 0;  // E. when a is a singleton - no need for the full E. treatment
  if(likely(m&1))R jtcombineeps;  // e. types: direct i.-family types, go to routine to vector there; postflags are 0
  // all that's left is E.
  R atcompX[m>>3];  // choose i.-family routine; postflags are 0
 }
}    /* function table look-up for  comp i. 1:  and  i.&1@:comp  etc. */
````

**Comment by plj541** [comment] 2022-06-15 16:29
Just to be sure everyone knows, all of these examples work as expected on my 64 bit Android, 
and fail on the 32 bit server. I assume the source of the builds have differences as well.
For what it is worth, I tried integers and got a wrong answer, but output still occurs.
  NB.====↓==== That E is UPPER CASE
   2 3 +/@E. 2 3 2 3   NB. Wrong answer
0
  +/ 2 3 E. 2 3 2 3
2

**Comment by joebo** [comment] 2022-06-15 16:55
Resolved with cba98bc31c503b5b2c6836f17312fb19401f191e as a workaround. The workaround disables special code paths found with jtatcompf. The root cause should still be investigated as time permits, but it's more important for the jengine to work correctly on WASM then to be fast with other non-failing special code paths.

**Closed as completed by joebo** 2022-06-15 16:55 UTC

**Comment by plj541** [comment] 2022-06-15 17:53
This is before I've done anything to the session.
   nl
|value error: nl
|[-0]
   cocurrent
|value error: cocurrent
|[-0]

**Comment by joebo** [comment] 2022-06-15 18:06
Thanks for testing. That was my mistake. I accidentally committed the WASM
bin data from the tests build not the html build. Should be fixed now. I
just checked and it works for me. Thanks again
