### ISSUE TITLE
Definitions appear twice when entered from Edit with {{ }}

### ISSUE THREAD

**Issue by plj541** [jsoftware/j-playground#77] opened 2022-05-27 08:00 UTC
now=.{{
 - y
}}

then=.{{
 (- y)* y
}}

**Comment by plj541** [comment] 2022-05-27 18:22
Also, click focus on the word now click Line or Ctrl+Enter and everything runs.

now=: {{
 -y
}}

then=: {{
(- y)* y
}}

yes=: 0 : 0
 'or no'
)

i.8

**Comment by cdburke** [comment] 2022-05-27 20:03
Right, closing }} on multiline direct definitions is not recognized. I am looking at this now.

**Comment by cdburke** [comment] 2022-05-28 17:54
Fixed now.

**Closed as completed by cdburke** 2022-05-28 17:54 UTC

**Comment by plj541** [comment] 2022-05-30 19:30
Wow, sometimes the simple puzzles take more time to see. When I first
reentered the initial report below, it failed worse than before. Since it
was Saturday, I thought maybe the system hadn't been updated. Then
sometimes in usage I noticed it worked, but I was on another issue and
didn't pursue. This morning I tried again, with both results. This time I
took the time to look. The difference between working, and the original
example below, is a space between :{

now=:{{
 -y
}}

then=:{{
(- y)* y
}}

**Comment by cdburke** [comment] 2022-05-30 20:58
I goofed, sorry. 

Since the {{ parsing code is quite complex, I wrote the parser in J, and then converted it to Javascript. I had used J word formation, but the Javascript replacement I used for that is not the same.

At least I know where the problem is.

**Comment by plj541** [comment] 2022-05-30 22:16
I didn't realize the parse you are using is written in JavaScript. I don't
know much about how you've presented J in this environment, but I'm curious
to know if there's a fundamental reason why you can't use the ability to
consume one line at a time.

I know when the Android version was first released, I couldn't create
functions inline, debug after a suspend or read a line with 1!:1 [1. I
don't remember the exact behavior of each, but the J-Playground seems to
have the same restrictions. With Android it was fixed by setting async
during initialization
  wd ''setj asyncj 1'
and then restarting.

If that could be done for this J, you wouldn't need most of the tricks I've
been reporting lately.

**Comment by cdburke** [comment] 2022-05-30 23:55
I reverted to using word formation in J. Please try again.

I think the problem with one line at a time is that in multiline definitions, there is no callback from the J engine for the next line. So if the first line is

  foo=: {{

then this will give an error.

The entire definition has to be read in and passed to J in a single step. Also, this is more convenient for the user, in that multiline definitions are treated as a single line.
