### ISSUE TITLE
ReferenceError and follow up

### ISSUE THREAD

**Issue by aries26** [jsoftware/j-playground#13] opened 2022-03-09 16:48 UTC
hello: as
   
hello:  sdad      NB. blank before 's'
   
hello: 123
   3+
|syntax error
|       3+
   
hello: ert
   (2!:0)'dir'
ERROR: ReferenceError: ertad is not defined

  Nothing works thereafter.

**Comment by joebo** [comment] 2022-03-09 17:02
Hello, can you paste the script / repl used to generate these outputs? I'm looking for a reproducible example. Even better would be to include a link from the permalink from the multi-line editor

![image](https://user-images.githubusercontent.com/151573/157492472-b0cfccd7-5d02-4c7e-916e-ca965b052092.png)

**Comment by aries26** [comment] 2022-03-09 18:28
Here is my full previous session.
`A browser-based J REPL. Type )h for help.
   )play
To execute code examples, click on line and press return/enter.

 3 + 2.3 7 4500 1.2e4                                NB. Add 3 to vector of numbers
 i. 3 4                                              NB. create matrix of integers
 %. 3 3 $ 243 252 234                                NB. invert 3 by 3 matrix
 ;: 'I read what I want to read'                     NB. split string into boxed words
 (~.,.<@#/.~);: 'I read what I want to read'         NB. group by unique word and count appearances
 (2!:0) 'alert("hello world")'                     NB. show alert popup
 smoutput 'hello: ', ((2!:0) 'prompt("name?")')    NB. interact with host javascript
 (1!:0) 'jlibrary/system/main/*.ijs'                 NB. list directory matching *.ijs 
   
hello: as
   
hello:  sdad
   
hello: 123
   3+
|syntax error
|       3+
   
hello: ert
   (2!:0)'dir'
ERROR: ReferenceError: ertad is not defined
3
   23
   `
So I was trying to "interact with host javascript", four times. See the smoutput line.


Then I tried the foreign.
In the error report, could the "ad" of "ertad" have something to do with the second hello?

If I use the editor and run:
`try. (2!:0) 'dir'
catch. 'error in try'
end.
`
I get
`   try. (2!:0) 'dir'
|spelling error
|   try. (2!:0) 'dir'
|   ^
|[-0] 
   345
345`
And this time I can continue with a new statement.

**Comment by aries26** [comment] 2022-03-09 18:30
After reloading to get your patch, the result is:
`A browser-based J REPL. Type )h for help.
   (2!:0)'dir'
length is 3
error`

**Comment by joebo** [comment] 2022-03-09 19:49
Thanks for the helpful error report. dir isn't a javascript function so you're getting an error because of that. We can improve the error message, but check out the javascript debugging tools in your browser for more info. You should see something like this:

![image](https://user-images.githubusercontent.com/151573/157522114-44b8842f-77ca-427d-91b7-fb9299e5d5ac.png)


I'm closing this issue for now since the patch seems to have fixed it. Happy to reopen it if there's a continuing problem or please open a new issue. Thanks again for the initial bug report.

```
   (2!:0) 'window.dir=function(){console.log("dir called"); return "nothing to see here";};dir()'
```

Should show

```
nothing to see here
```

I will fix the 'length is...' debugging message

**Closed as completed by joebo** 2022-03-09 19:49 UTC
