### ISSUE TITLE
Initial parts of Comment do no appear in output, also output cannot be copied

### ISSUE THREAD

**Issue by plj541** [jsoftware/j-playground#63] opened 2022-05-24 01:09 UTC
Previously mentioned in issue #53, but subject of that report only mentioned duplicate output.
                  NB.     Note ''     )
Are not output from running following lines.  
===== Edit Run > All Lines =====
NB. single line comment
NB.    another single line comment

Note ''
multiline
comment
)

NB. verb definition

===== Yields this in Term =====
single line comment
   another single line comment
multiline
comment

verb definition

===== Nothing in Term appears with Copy/Paste =====

**Comment by cdburke** [comment] 2022-05-24 01:58
Do you mean that the NB. and Note '' are not shown in the output? That was by design, so that only the comment text appears and is in a different format from the rest of the session. 

I don't feel strongly about this, though I rather like it the way it is now.

**Comment by plj541** [comment] 2022-05-24 06:22
Yes, that is what I'm referring to. Is the failure to copy those lines also
intentional? This led me to wonder if they print, I'm happy to say they do,
as do plots. Although I can only print what is currently showing on my
screen, not a full session web page as other sites allow. Since I'm using a
tablet, it is easy for me to increase screen length.

Deleting the NB. strikes me as a little strange because it looks different
than any output session manager I have used. Unless J has similar session
managers, it seems a little strange to introduce people to features they
won't be able to get when using the product directly.

**Comment by plj541** [comment] 2022-05-24 16:03
I'm sorry I'm so slow on the uptake. It took thinking about my comment:
    I can only print what is currently showing on my screen
To realize both Term and Edit are html textareas, especially since my ten
year old APL.js session manager had exactly the same limitations.

**Comment by rdm** [comment] 2022-05-24 17:44
> Yes, that is what I'm referring to. Is the failure to copy those lines also intentional? This led me to wonder if they print, I'm happy to say they do, as do plots. Although I can only print what is currently showing on my screen, not a full session web page as other sites allow. Since I'm using a tablet, it is easy for me to increase screen length. Deleting the NB. strikes me as a little strange because it looks different than any output session manager I have used. Unless J has similar session managers, it seems a little strange to introduce people to features they won't be able to get when using the product directly.

... unless this feature of the playground is added to other IDEs.

That said, it might eventually be worth making it configurable. **Maybe**... (this mechanism seems to go hand-in-hand with the side-by-side script and session window structure ...).

That said, there's underlying conflicts between clean presentation, clean serialization and clean implementation. And I think the separation of script and session already gives us a lever there (we can copy from the script or from the session).

**Comment by cdburke** [comment] 2022-05-24 18:11
In the playground, comments are shown in green text, whereas in Jqt they have no special markup. I thought this difference would be enough to justify dropping off the comment markers.

Like Jqt, the edit session is the proper source, and the term session primarily for output. 

Note also that comments do not appear in the Input log.

**Comment by plj541** [comment] 2022-05-24 20:06
Not having a 'comment only line' appear in the Input Log is a nice touch.

This suggests that  a 'comment only line' is not copied by design. Please
note, since Labs also produces green input and output, those lines cannot
be copied either.

**Comment by joebo** [comment] 2022-05-27 20:24
Closing with fix #68 . Feel free to reopen if I missed something

**Closed as completed by joebo** 2022-05-27 20:24 UTC
